Repository crowdsourcemedical/volunteer-database, pull requests merged in 2020-03, with the labels that each got.

#16 Update readme with PR process information
  README.md
Labels: documentation

#26 Various backend cleanup
  .github/workflows/backend.yml
  backend/.coveragerc
  backend/Dockerfile
  backend/Makefile
  backend/app/crud.py
  backend/app/database.py
  backend/app/main.py
  backend/app/models.py
  backend/app/schemas.py
  backend/app/utils.py
  backend/pytest.ini
  backend/requirements.txt
  backend/tests/integration/.gitkeep
  backend/tests/unit/test_simple.py
Labels: enhancement

#44 Add GETTING_STARTED.md
  GETTING_STARTED.md
Labels: documentation

#40 Enabling unit and functional testing of API
  backend/Makefile
  backend/app/database.py
  backend/app/main.py
  backend/app/tests/__init__.py
  backend/app/tests/conftest.py
  backend/app/tests/test_crud.py
  backend/app/tests/test_main.py
  backend/pytest.ini
  backend/tests/unit/test_simple.py
Labels: enhancement

#60 Expanding on GETTING_STARTING.md
  GETTING_STARTED.md
Labels: documentation

#56 Backend auth system
  backend/Makefile
  backend/app/auth.py
  backend/app/crud.py
  backend/app/database.py
  backend/app/main.py
  backend/app/models.py
  backend/app/routers/users.py
  backend/app/tests/conftest.py
  backend/app/tests/test_auth.py
  backend/app/tests/test_main.py
  backend/app/utils.py
  backend/requirements.txt
  docker-compose.yml
Labels: enhancement

#71 Mobile Search
  frontend/src/components/Search/Filters.jsx
  frontend/src/components/Search/MobileSearch.jsx
  frontend/src/components/Search/PeopleFilters.jsx
  frontend/src/components/Search/PersonResult.jsx
  frontend/src/components/Search/ProjectFilters.jsx
  frontend/src/components/Search/SearchResults.jsx
  frontend/src/components/navbar.jsx
  frontend/src/images/jane-doe-profile-pic.png
Labels: Needs Review

#95 Mobile Project Page
  frontend/src/pages/project.jsx
Labels: Needs Review

#100 Updated Models, Updated Auth, Updated JWT, Added JWT Secret, Cleanup,…
  backend/app/JWT.py
  backend/app/auth.py
  backend/app/crud.py
  backend/app/main.py
  backend/app/models.py
  backend/app/schemas.py
Labels: Needs Review

#109 Search Bar updated for mobile + some other changes
  frontend/src/components/Header.jsx
  frontend/src/components/Search/SearchBar.jsx
  frontend/src/components/Search/SearchResults.jsx
  frontend/src/pages/home.jsx
Labels: Needs Review
